### ISSUE TITLE
Export Analysis does not work

### ISSUE THREAD

**Issue by sorenhejgaard** [Campbell-Muscle-Lab/GelBox#7]
After completing my analysis of my western blotting analysis via your tutorial, I will export the analysis to an excel file.

However, after choosing a name and a folder, it will not save. I can see that the file was saved but it's completely empty:
![Skærmbillede 2024-08-24 105740](https://github.com/user-attachments/assets/dad9a3d2-25ef-4847-b6e5-e0ad9169749e)

The final blot with boxes on top looks like this:
![Skærmbillede 2024-08-24 110002](https://github.com/user-attachments/assets/e7c87e9d-97fa-4776-9c6f-05b572728868)

The saving interface looks like this:
![Skærmbillede 2024-08-24 105903](https://github.com/user-attachments/assets/4036d17a-625d-4b39-95c0-fc40c1f91e2a)

Either it's a software error or somehow I did not produce a result which seems unlikely.

Thanks so much for your help and for a otherwise really useful programme!

**Comment by kenatcampbellmusclelab** [comment]
Hi Sorenejgaard,

GelBox analysis assumes that the background is lighter than the bands. You can invert the image within GelBox as described here.

https://campbell-muscle-lab.github.io/GelBox/pages/tutorial/start_new_analysis/start_new_analysis.html

![image](https://github.com/user-attachments/assets/f421fb86-0b04-4f8d-b22e-70755970de32)

**Comment by sorenhejgaard** [comment]
Hi Ken,

Thank you so much for your reply!

But I think you misunderstood my issue. I don’t have a problem with the inverted image. I struggle with exporting the analysis as an excel file after my analysis. The file seems to be generated but it’s empty.

Best
Søren
________________________________
Fra: Ken Campbell ***@***.***>
Sendt: Saturday, August 24, 2024 6:38:56 PM
Til: Campbell-Muscle-Lab/GelBox ***@***.***>
Cc: sorenhejgaard ***@***.***>; Author ***@***.***>
Emne: Re: [Campbell-Muscle-Lab/GelBox] Export Analysis does not work (Issue #7)


Hi Sorenejgaard,

GelBox analysis assumes that the background is lighter than the bands. You can invert the image within GelBox as described here.

https://campbell-muscle-lab.github.io/GelBox/pages/tutorial/start_new_analysis/start_new_analysis.html

image.png (view on web)<https://github.com/user-attachments/assets/f421fb86-0b04-4f8d-b22e-70755970de32>

**Comment by utkugulbulak** [comment]
Hello @sorenhejgaard,

Sorry for the inconvenience. I'd like to reproduce your issue to pinpoint the source. To do so:

Can you please let me know which version (Matlab app or standalone) of GelBox are you using? 

Can you please try and save the analysis as a GBX file and reply to this thread as an attachment?

Thank you so much for using GelBox and again sorry for the inconvenience.

Have a great day!

Utku

**How to save GBX files:**
![image](https://github.com/user-attachments/assets/688cf74e-b09e-491b-acb4-8567e6d9e457)

**Comment by sorenhejgaard** [comment]
Hi Utku,

Yes, of course, thank you.

I am using the standalone app and it’s the latest version (GelBox-1.1) as I downloaded it last week.

Attached is the GBX file for the analysis. FYI, I also loaded a lane layout from excel which seemed to work.

Thank you for your help! 😊

Best
Søren

Fra: utkugulbulak ***@***.***>
Sendt: 27. august 2024 23:12
Til: Campbell-Muscle-Lab/GelBox ***@***.***>
Cc: sorenhejgaard ***@***.***>; Mention ***@***.***>
Emne: Re: [Campbell-Muscle-Lab/GelBox] Export Analysis does not work (Issue #7)


Hello @sorenhejgaard<https://github.com/sorenhejgaard>,

Sorry for the inconvenience. I'd like to reproduce your issue to pinpoint the source. To do so:

Can you please let me know which version (Matlab app or standalone) of GelBox are you using?

Can you please try and save the analysis as a GBX file and reply to this thread as an attachment?

Thank you so much for using GelBox and again sorry for the inconvenience.

Have a great day!

Utku

How to save GBX files:
image.png (view on web)<https://github.com/user-attachments/assets/688cf74e-b09e-491b-acb4-8567e6d9e457>

**Comment by utkugulbulak** [comment]
Hello @sorenhejgaard,

I hope you are doing well. I pushed a new version of GelBox where users can export analysis without a gel layout.

Please let me know if the issue persists for you.

Have a great weekend.

Utku

![soren_trial](https://github.com/user-attachments/assets/ff1b9239-907f-4883-a15e-ae73734dcd13)

**Comment by sorenhejgaard** [comment]
Hi Utko,

Thank you so much! It seems to work again.

Kind regards
Søren



Fra: utkugulbulak ***@***.***>
Sendt: 31. august 2024 04:26
Til: Campbell-Muscle-Lab/GelBox ***@***.***>
Cc: sorenhejgaard ***@***.***>; Mention ***@***.***>
Emne: Re: [Campbell-Muscle-Lab/GelBox] Export Analysis does not work (Issue #7)


Hello @sorenhejgaard<https://github.com/sorenhejgaard>,

I hope you are doing well. I pushed a new version of GelBox where users can export analysis without a gel layout.

Please let me know if the issue persists for you.

Have a great weekend.

Utku

soren_trial.PNG (view on web)<https://github.com/user-attachments/assets/ff1b9239-907f-4883-a15e-ae73734dcd13>

-
